Website = "https://github.com/bytemystery-com/passwordsafe"

[Details]
Icon = "assets/icons/icon.png"
Name = "PasswordSafe"
ID = "com.bytemystery.passwordsafe2"
Version = "0.3.6"
Build = 254

[LinuxAndBSD]
GenericName = "PasswordSafe"
Categories = ["System"]
Comment = "Store passwords in a safe way"
Keywords = ["password", "store", "crypt"]
